### ISSUE TITLE
Nativefier Fails When Instructed to Use Compression and an Icon

### ISSUE THREAD

**Issue by Ulric19** [jiahaog/nativefier#233]
### Description
When I try to wrap a web app using nativefier, giving it arguments to use a specific icon and to compress the app folder to app.asar, the process fails.

### Steps to Reproduce Issue
A generic example. The icon is located in the current working directory.
nativefier --name "Google" -i "./new-google-favicon-128.png" "http://www.google.com" -c

### Specifications
- Version of Nativefier: `v7.0.1`
- Version of Node.js: `v4.4.7`
- OS: `Ubuntu 14.04`
- Architecture `x64`
- Stack trace from the error message :
```
Packaging app for platform linux x64 using electron v1.1.3
[ { [Error: ENOENT: no such file or directory, open '/home/<username>/apps/Google-linux-x64/resources/app/icon.png']
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/<username>/apps/Google-linux-x64/resources/app/icon.png' } ]
```
Any help would be greatly appreciated. Thanks.

**Comment by ronjouch** [comment]
Bug confirmed under Nativefier 7.1.0 / Electron 1.6.6

```bash
~ nativefier -e 1.6.6 --name "testasaricon" -c --icon "/opt/feedly.png" "https://feedly.com/i/latest"
Packaging app for platform linux x64 using electron v1.6.6
[ { Error: ENOENT: no such file or directory, open '/home/ronj/testasaricon-linux-x64/resources/app/icon.png'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/ronj/testasaricon-linux-x64/resources/app/icon.png' } ]
```

**Comment by darrenhaken** [comment]
Picking this up

**Comment by darrenhaken** [comment]
I just ran `nativefier -e 1.6.6 --name "testasaricon" -c --icon "~/Downloads/feedly.png" "https://feedly.com/i/latest"` and it all worked fine for me. @ronjouch is this fixed now?

Running off latest master `b467ac7a514950ea9f3090928a3bb72e0cf0c282`

**Comment by ronjouch** [comment]
Weird, I can still reproduce it. Assigning to myself, will look at it.

**Comment by jasonwang178** [comment]
Hi, any news on this?

**Comment by majorcyto** [comment]
Hi, Any news on this?

**Comment by jasonhansel** [comment]
I can reproduce the issue with nativefier 7.4.1. Curiously, it also happens to me when `-i` is *not* specified; `nativefier https://fastmail.com --conceal` prints out:
```
Packaging app for platform linux x64 using electron v1.6.6
[ { Error: ENOENT: no such file or directory, open '/home/jason/Desktop/get-secure-reliable-email-hosting-fast-mail-linux-x64/resources/app/icon.png'
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/home/jason/Desktop/get-secure-reliable-email-hosting-fast-mail-linux-x64/resources/app/icon.png' } ]
```

**Comment by lojmax** [comment]
Encountered the same problem. 
Are there any workarounds, or upcoming fixes for this issue?

**Comment by i7voodoo** [comment]
Still have the same problem

**Comment by spikespaz** [comment]
Same problem

**Comment by sorhtyre** [comment]
Corrected by [PR 1074](https://github.com/jiahaog/nativefier/pull/1074)?
