### ISSUE TITLE
On Windows, launching from custom URL produces popup that says "Electron"

### ISSUE THREAD

**Issue by realyze** [jiahaog/nativefier#390]
When I register my nativefier app as the default protocol handler and then open "myapp://" in Firefox, the popup says open with "Electron".

This string corresponds to the registry key `HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache`. From googling around, it looks like this should be set to the value of `FileDescription`...but for some reason it's set to "Electron".

**Comment by ronjouch** [comment]
@realyze thanks for the feedback! That should be fixed with merged-yesterday-but-yet-to-be-released https://github.com/jiahaog/nativefier/pull/389 . Try [running a development version](https://github.com/jiahaog/nativefier/blob/master/docs/development.md) to get it now, or wait for a release. At any rate, feedback welcome if it's still broken 🙂.

**Comment by realyze** [comment]
@ronjouch I'm actually using the version from yesterday (including the fix for #28) but this is still happening. The Task Manager app name is now correct but the Launch with is not...

BTW thanks for nativefier, it's a brilliant tool!

**Comment by ronjouch** [comment]
@realyze hm okay, reopening. Thanks for the fast feedback 👍.

**Comment by realyze** [comment]
Hmmm, wait, actually, I might just be FUDing you unintentionally. :-) The name is correct now, after I uninstalled the app, restarted the windows machine and reinstalled.

Do you ming keeping this open for a few hours till I confirm whether it's working?

**Comment by realyze** [comment]
I've had the app installed on the machine which was done from earlier version of Nativefier, so I might be seeing cache ghosts.

**Comment by ronjouch** [comment]
Fantasbulous, no worry, take your time to in/confirm things are okay now, and we'll re-open as needed

**Comment by realyze** [comment]
Cool, so FriendlyAppName seems to be set OK. But the `companyName` is always set to `GitHub` which is definitely not us. :-) Is there any override for that? Our `package.json` specifies the `author` field but it doesn't seem to be respected (if that's the one that should set it).

**Comment by realyze** [comment]
I guess https://github.com/jiahaog/nativefier/issues/226 maybe?

**Comment by ronjouch** [comment]
> I guess #226 maybe?

Yeah, looks like, and #226 was fixed by https://github.com/jiahaog/nativefier/pull/244 , but with a fix that end up remaining unmerged. If you have the time/knowledge for that and since you can reproduce the current problem and confirm the fix, a rebase of #244 would be most welcome.

**Comment by realyze** [comment]
I'll write that into my scribblepost. With a bit of luck, I could have a swing at it later this week. Thanks for your help!
