### ISSUE TITLE
Copy Current URL only copies URL from first window, not secondary windows

### ISSUE THREAD

**Issue by dsemaya** [jiahaog/nativefier#409]
### Description
Choosing `Edit`: `Copy Current URL` (Ctrl+L) will only copy the URL from the first window in a Nativefier app, even if a secondary window is in the foreground.

### Steps to Reproduce Issue
Make a Nativefier app of Google Drive.
In the first window double click on a document to spawn a second window.
While the document window is on top, use Copy Current URL.

Results: The URL of the Drive (first) window is copied, not the document (second) window.  

### Specifications
- Version of Nativefier (run `$ nativefier --version`): `v7.4.0`
- Version of Node.js (run `$ node --version`): `v6.9.1`
- OS: `macOS 10.12.5`
- Architecture `x86`

**Comment by ronjouch** [comment]
Bug reproduced, thanks for the feedback @dsemaya 👍.

**Comment by JMarteF** [comment]
Is this issue closed? Apparently it seems to work with the latest version of nativefier v7.6.7

**Comment by bacongravy** [comment]
This was likely resolved with PR #588.

**Comment by JMarteF** [comment]
Oh, Okay. Thank you! Do you know of any other issues that might be already resolved but still not closed? I'm trying to target some issues but some of them seem to be resolved already.

**Comment by bacongravy** [comment]
I did the same a few months ago, I'm surprised I missed this one.  Thanks for verifying that it no longer needs to be fixed.  I don't know of any other already-resolved issues.

**Comment by ronjouch** [comment]
@JMarteF thanks for noticing 🙂, closing the issue then. Regarding...

> *"Do you know of any other issues that might be already resolved but still not closed? I'm trying to target some issues but some of them seem to be resolved already."*

, well I (occasional maintainer for a few years) lost interest in Nativefier since [Firefox Containers](https://support.mozilla.org/en-US/kb/containers), so I've been slacking on issue triaging during the last months. Feel free to mention other issues that seem resolved and I'll close them. And go ahead and target anything, all help welcome 🙂.

And @bacongravy, your contributions were of excellent quality, if anything tickles you in Nativefier or if you want to get more involved in some other part of Nativefier, don't hesitate to reach out.
