### ISSUE TITLE
[ts] app icon missing (error while converting to PNG)

### ISSUE THREAD

**Issue by leinardi** [jiahaog/nativefier#906]
### Description

the app icon is missing from the tray:
![image](https://user-images.githubusercontent.com/273338/74604874-81378b80-50c2-11ea-8419-c97f643ef3a0.png)

### Steps to reproduce issue

1. try to nativefy https://teams.webex.com
2. check the tray icon (or, better, the absence of it)

### Details

- Are you nativefying a *public* website? yes
- Full nativefier command used to build your app: `nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 8.0.1 --tray --single-instance --counter --bounce --honest https://teams.webex.com --verbose`
- Version of Nativefier (run `nativefier --version`): `53a92de14921103a59ae640bd1d635a91181db60`
- Version of node.js (run `node --version`): `v10.15.2`
- OS: `Ubuntu 19.10`
- Error message / stack trace (if any):

```
$ nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 8.0.1 --tray --single-instance --counter --bounce --honest https://teams.webex.com --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Inferring user agent for electron 8.0.1 / linux
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Inferring icon for https://teams.webex.com/ on linux
Inferring icon from store for https://teams.webex.com/ on linux
Allowed icon formats when building for linux: [ '.png', '.ico' ]
Got name Webex-Teams from options. No inferring needed
Sanitized filename for Webex-Teams : Webex-Teams
Inferring name for https://teams.webex.com/
Got 249 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Fetched 1.7 kb page at https://teams.webex.com/
Inferred title: Sign in to Webex Teams
Sanitized filename for Sign in to Webex Teams : SignintoWebexTeams
Associated electron v8.0.1 to chrome v80.0.3987.86
Given chrome 80.0.3987.86 on linux, using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.86 Safari/537.36
Got an icon from the page.
Writing 148.6 kb icon to /tmp/nativefier-13-43-20-iconinfer-38513IsSd11dGg9t/icon.ico

Preparing Electron app...
Copying electron app from /home/leinardi/Workspace/github/nativefier/app to /tmp/nativefier-13-43-20-app-3851FWMmiSkj3v6W
Writing app config to /tmp/nativefier-13-43-20-app-3851FWMmiSkj3v6W/nativefier.json
No files to inject, skipping copy.
Updating /tmp/nativefier-13-43-20-app-3851FWMmiSkj3v6W/package.json 'name' field to signintowebexteams-nativefier-ff9bb8

Converting icons...
Converting icon /tmp/nativefier-13-43-20-iconinfer-38513IsSd11dGg9t/icon.ico to /tmp/nativefier-13-43-20-iconconv-3851JkTgmj4Fc0P5/icon.png. Calling: "/home/leinardi/Workspace/github/nativefier/lib/icon-scripts/convertToPng" "/tmp/nativefier-13-43-20-iconinfer-38513IsSd11dGg9t/icon.ico" "/tmp/nativefier-13-43-20-iconconv-3851JkTgmj4Fc0P5/icon.png"
Failed to convert icon to .png, skipping. { stdOut: '',
  stdError:
   '/bin/sh: 1: /home/leinardi/Workspace/github/nativefier/lib/icon-scripts/convertToPng: not found\n' }

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 14.2.1
  electron-packager Node v10.15.2
  electron-packager Host Operating system: linux 5.3.0-29-generic (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-13-43-20-app-3851FWMmiSkj3v6W","electronVersion":"8.0.1","icon":"/tmp/nativefier-13-43-20-iconinfer-38513IsSd11dGg9t/icon.ico","name":"SignintoWebexTeams","out":"/home/leinardi/Workspace/github/nativefier","overwrite":true,"platform":"linux","targetUrl":"https://teams.webex.com/","tmpdir":false,"win32metadata":{"ProductName":"Webex-Teams","InternalName":"Webex-Teams","FileDescription":"Webex-Teams"}} +0ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-13-43-20-app-3851FWMmiSkj3v6W/package.json +0ms
  electron-packager Application name: SignintoWebexTeams +5ms
  electron-packager Target Electron version: 8.0.1 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager' ] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"8.0.1","artifactName":"electron"} +0ms
Packaging app for platform linux x64 using electron v8.0.1
  electron-packager Creating /home/leinardi/Workspace/github/nativefier/linux-x64-template +2ms
  electron-packager Extracting /home/leinardi/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.0.1electron-v8.0.1-linux-x64.zip/electron-v8.0.1-linux-x64.zip to /home/leinardi/Workspace/github/nativefier/linux-x64-template +0ms
  electron-packager Initializing app in /home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-x64 from /home/leinardi/Workspace/github/nativefier/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-darwin-x64',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-ia32',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-x64',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-armv7l',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-arm64',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-mips64el',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-mas-x64',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-win32-ia32',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-win32-x64',
  '/home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-win32-arm64' ] +1s
  electron-packager Renaming electron to SignintoWebexTeams in /home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-x64 +99ms

Finalizing build...
Copying icons if necessary
Copying icon /tmp/nativefier-13-43-20-iconinfer-38513IsSd11dGg9t/icon.ico to /home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-x64/resources/app/icon.ico
App built to /home/leinardi/Workspace/github/nativefier/SignintoWebexTeams-linux-x64
```

In the current master the icon is correctly shown:
```
$ nativefier --name "Webex-Teams" --platform linux --arch x64 --electron-version 8.0.1 --tray --single-instance --counter --bounce --honest https://teams.webex.com --verbose
  icons [==============================                    ] 60%Packaging app for platform linux x64 using electron v8.0.1

App built to /home/leinardi/Workspace/github/nativefier/Webex-Teams-linux-x64
```

**Comment by ronjouch** [comment]
@leinardi thanks! Fixed in dd192c749063ec54e486c40c5f8b072569f05dbe ! Thanks a lot for the testing 🙂! Keep it coming if you see more broken tests.

**Comment by leinardi** [comment]
Hi, I tried again and the icon was still missing:

```
nativefier -n "Webex-Teams" -p linux -a x64 -e 8.0.1  --tray --single-instance --counter --honest --min-width 970 --min-height 680 https://teams.webex.com --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Inferring user agent for electron 8.0.1 / linux
Grabbing electron<->chrome versions file from https://atom.io/download/atom-shell/index.json
Inferring icon for https://teams.webex.com/ on linux
Inferring icon from store for https://teams.webex.com/ on linux
Allowed icon formats when building for linux: [ '.png' ]
Got name Webex-Teams from options. No inferring needed
Sanitized filename for Webex-Teams : Webex-Teams
Got 249 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Got an icon from the page.
Writing 148.6 kb icon to /tmp/nativefier-9-36-19-iconinfer-7977IJAT1DK4R1eN/icon.ico
Unable to infer chrome version for user agent, using 78.0.3904.130
Given chrome 78.0.3904.130 on linux, using user agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.130 Safari/537.36

Preparing Electron app...
Copying electron app from /home/rleinardi/temp/nativefier/app to /tmp/nativefier-9-36-19-app-7977wJJ617tlTg3R
Writing app config to /tmp/nativefier-9-36-19-app-7977wJJ617tlTg3R/nativefier.json
No files to inject, skipping copy.
Updating /tmp/nativefier-9-36-19-app-7977wJJ617tlTg3R/package.json 'name' field to webex-teams-nativefier-ff9bb8

Converting icons...
Converting icon /tmp/nativefier-9-36-19-iconinfer-7977IJAT1DK4R1eN/icon.ico to /tmp/nativefier-9-36-19-iconconv-79776wyGy4yjM6vt/icon.png. Calling: "/home/rleinardi/temp/nativefier/icon-scripts/convertToPng" "/tmp/nativefier-9-36-19-iconinfer-7977IJAT1DK4R1eN/icon.ico" "/tmp/nativefier-9-36-19-iconconv-79776wyGy4yjM6vt/icon.png"
Failed to convert icon to .png, skipping. {
  stdOut: '',
  stdError: 'Cannot find required ImageMagick Convert executable\n'
}

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 14.2.1
  electron-packager Node v12.14.1
  electron-packager Host Operating system: linux 5.4.13-201.fc31.x86_64 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-9-36-19-app-7977wJJ617tlTg3R","electronVersion":"8.0.1","icon":"/tmp/nativefier-9-36-19-iconinfer-7977IJAT1DK4R1eN/icon.ico","name":"Webex-Teams","out":"/home/rleinardi","overwrite":true,"platform":"linux","targetUrl":"https://teams.webex.com/","tmpdir":false,"win32metadata":{"ProductName":"Webex-Teams","InternalName":"Webex-Teams","FileDescription":"Webex-Teams"}} +0ms
  electron-packager Target Platforms: linux +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-9-36-19-app-7977wJJ617tlTg3R/package.json +0ms
  electron-packager Application name: Webex-Teams +6ms
  electron-packager Target Electron version: 8.0.1 +0ms
  electron-packager Ignored path regular expressions: [
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"8.0.1","artifactName":"electron"} +0ms
Packaging app for platform linux x64 using electron v8.0.1
  electron-packager Creating /home/rleinardi/linux-x64-template +2ms
  electron-packager Extracting /home/rleinardi/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv8.0.1electron-v8.0.1-linux-x64.zip/electron-v8.0.1-linux-x64.zip to /home/rleinardi/linux-x64-template +1ms
  electron-packager Initializing app in /home/rleinardi/Webex-Teams-linux-x64 from /home/rleinardi/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  '/home/rleinardi/Webex-Teams-darwin-x64',
  '/home/rleinardi/Webex-Teams-linux-ia32',
  '/home/rleinardi/Webex-Teams-linux-x64',
  '/home/rleinardi/Webex-Teams-linux-armv7l',
  '/home/rleinardi/Webex-Teams-linux-arm64',
  '/home/rleinardi/Webex-Teams-linux-mips64el',
  '/home/rleinardi/Webex-Teams-mas-x64',
  '/home/rleinardi/Webex-Teams-win32-ia32',
  '/home/rleinardi/Webex-Teams-win32-x64',
  '/home/rleinardi/Webex-Teams-win32-arm64'
] +1s
  electron-packager Renaming electron to Webex-Teams in /home/rleinardi/Webex-Teams-linux-x64 +167ms

Finalizing build...
Copying icons if necessary
Copying icon /tmp/nativefier-9-36-19-iconinfer-7977IJAT1DK4R1eN/icon.ico to /home/rleinardi/Webex-Teams-linux-x64/resources/app/icon.ico
App built to /home/rleinardi/Webex-Teams-linux-x64
```

I then noticed this error:
```
Failed to convert icon to .png, skipping. {
  stdOut: '',
  stdError: 'Cannot find required ImageMagick Convert executable\n'
}
```

after installing it the icon was converted correctly. 
Probably the README should be updated including also Linux: https://github.com/jiahaog/nativefier#icon-conversion-for-macos

**Comment by ronjouch** [comment]
> After installing [imagemagick], the icon was converted correctly.
> Probably the README should be updated including also Linux: [jiahaog/nativefier#icon-conversion-for-macos](https://github.com/jiahaog/nativefier#icon-conversion-for-macos)

@leinardi yup, done. This is not new, you confirm? Put differently, on your machine *without* imagemagick installed, if you run the same command with Nativefier 7.7.1 stable, you won't get an icon either. Correct?

Also, the problem must be clearer without the `--verbose` flag, which here sinks the error under tons of output. Right?
